[package]
name = "anchor"
version = "0.1.0"
edition = "2021"

[dependencies]
ink = { version = "5.0", default-features = false }

[lib]
name = "anchor"
path = "lib.rs"
crate-type = ["cdylib", "rlib"]

[profile.release]
panic = "abort"
lto = true
